### PR TITLE
Handling for listen-only connections

### PR DESCRIPTION
**Pull request by OE3ANC**
Hi,

with these changes it is now possible to connect with clients using the magic "LSTN" and a callsign starting with "SWL" followed by 6 additional letters (e.g. SWLABCDEF). This will open a "listen-only" client connection. 

Nodes will have an additional listenonly bool in mrefd.xml, so listen-only nodes can be distinguished from normal nodes.

It is also possible to disable logging of SWL clients to mrefd.xml and to disable listening to encrypted channels for listen-only nodes. There are 2 new entries in the mrefd.cfg for this:

```
# Allow connections from listen-only clients to modules with encryption support
ListenOnlyAllowEncrypt = false

# Export listen-only clients to the mrefd.xml for the use in dashboards
ListenOnlyLogging = false
```

Please let me know what you think

73, Andy

### CODE REVIEW

**Comment by n7tae** [comment]
Several things:

- Please move your trap for transmissions from LO clients upstream to CProtocol::OnFirstPacketIn().
- You don't need an extra constructor for CClient. Just add your `listenOnly` bool parameter to the end of the list in the parameterized constuctor. In Client.h set it to `false`, and in Client.cpp add your assignment `m_listenOnly = listenOnly;`.
- Please add the LSTN packet description to the M17-ref-packet-description.ods spreadsheet. This is the only place that officially describes all packets that mrefd consumes and produces.
- There are plenty of SWL listeners that don't have "SWL" in their callsigns and there are plenty of hams that may want to set up a LO client using their ham callsign. How about an LO regex of `^[0-9]?[A-Z][A-Z0-9]{2,8}$`?
- I can't think of any reason why an admin would want to hide LO clients, and if he did hid them, there will be no way of knowing how many there are.

**Comment by OE3ANC** [comment]
Thank you for reviewing and for the input!

Do you think it would make sense, to allow to append additional characters like for regular callsigns? (e.g. for the "D" that droidstar appends to the call). LO regex would be ``` "^[0-9]?[A-Z][A-Z0-9]{2,8}([ -/\\.].*)?$" ```

**Comment by OE3ANC** [comment]
I pushed the changes that i've done in the last view days:

- I've moved the trap for LO transmissions to ```OnFirstPacketIn```: If the client is LO, the packet will be released
- The extra constructor in CClient is now removed
- The LSTN packet is now documented in the M17-ref-packet-description.ods speadsheet
- The lstnRegex is now ```"^[0-9]?[A-Z][A-Z0-9]{2,8}$"```  as you suggested
- I removed the possibility to disable LO Client logs to mrefd.xml
- LO flag switch for the client is now done with help of the magic instead of the call
- Added 2 missing lstnRegex checks i found during testing

**Comment by vk3jed** [comment]
>     * I can't think of any reason why an admin would want to hide LO clients, and if he did hid them, there will be no way of knowing how many there are.

Yeah I'd like to be able to log/display listen only clients, but have the ability to list them separately on my dashboard, which I suspect that would be a function of the dashboard rather than mrefd, at least while we're using SWLxxxxxx callsigns for listen only connections. 

I can't comment on the coding, but I do like where this PR and the discussion is going.  I will definitely be making use of this feature when it's released.

**Comment by n7tae** [comment]
@OE3ANC , before I accept this, I just want to be sure gomrefdash still works. The additional parameter in the XML file hasn't caused any problems for the dashboard, has it?

**Comment by OE3ANC** [comment]
No problems with the build from the latest master branch. It's running with a listen only client connected at the moment on [M17-XOR](https://ref.oe3xor.at). Also no errors in gomrefdashs log.

**Comment by n7tae** [comment]
Thank you!

**Pull request merged**
